config/routes.rb
Rails.application.routes.draw do
  resources :shops
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :shop

  validates :title, presence: true
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :books, dependent: :destroy

  validates :name, presence: true

  accepts_nested_attributes_for :books
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  before_action :set_shop, only: %i[ show edit update destroy ]

  # GET /shops or /shops.json
  def index
    @shops = Shop.all
  end

  # GET /shops/1 or /shops/1.json
  def show
  end

  # GET /shops/new
  def new
    books = (1..2).map { Book.new }
    @form = ShopForm.new(Shop.new(books: books))
  end

  # GET /shops/1/edit
  def edit
    @form = ShopForm.new(Shop.find(params[:id]))
  end

  # POST /shops or /shops.json
  def create
    books = (1..2).map { Book.new }
    @form = ShopForm.new(Shop.new(books: books))

    if @form.validate(shop_params)
      @form.save
      redirect_to shop_path(@form.model)
    else
      render :new
    end
  end

  # PATCH/PUT /shops/1 or /shops/1.json
  def update
    @form = ShopForm.new(Shop.find(params[:id]))

    if @form.validate(shop_params)
      @form.save
      redirect_to shop_path(@shop)
    else
      render :edit
    end
  end

  # DELETE /shops/1 or /shops/1.json
  def destroy
    @shop.destroy
    respond_to do |format|
      format.html { redirect_to shops_url, notice: "Shop was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_shop
      @shop = Shop.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def shop_params
      params.fetch(:shop, {}).permit(:id, :name, :address, books_attributes: [:id, :title, :description])
    end
end

app/views/books/_book.html.erb
<div id="<%= dom_id book %>">
  <p>
    <strong>Title:</strong>
    <%= book.title %>
  </p>

  <p>
    <strong>Description:</strong>
    <%= book.description %>
  </p>

</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>FormSampleApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/shops/_form.html.erb
<%= form_with(model: form, data: { turbo: false }) do |shop_form| %>
  <% if form.errors.present? %>
    <div style="color: red">
      <h2><%= pluralize(form.errors.full_messages.count, "error") %> prohibited this shop from being saved:</h2>
      <ul>
        <% form.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= shop_form.label :name, style: "display: block" %>
    <%= shop_form.text_field :name %>
  </div>

  <div>
    <%= shop_form.label :address, style: "display: block" %>
    <%= shop_form.text_field :address %>
  </div>

  <h2> Books </h2>

  <div>
    <%= shop_form.fields_for :books do |book_form| %>
      <p><%= label_tag :title %>
      <p><%= book_form.text_field :title %>

      <p><%= label_tag :description %>
      <p><%= book_form.text_field :description %>
    <% end %>
  </div>
  <div>
    <%= shop_form.submit %>
  </div>
<% end %>

app/views/shops/_shop.html.erb
<div id="<%= dom_id shop %>">
  <p>
    <strong>Name:</strong>
    <%= shop.name %>
  </p>

  <p>
    <strong>Address:</strong>
    <%= shop.address %>
  </p>

</div>

app/views/shops/edit.html.erb
<h1>Editing shop</h1>

<%= render "form", form: @form %>

<br>

<div>
  <%= link_to "Show this shop", @shop %> |
  <%= link_to "Back to shops", shops_path %>
</div>

app/views/shops/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Shops</h1>

<div id="shops">
  <% @shops.each do |shop| %>
    <%= render shop %>
    <p>
      <%= link_to "Show this shop", shop %>
    </p>
  <% end %>
</div>


<%= link_to "New shop", new_shop_path %>

app/views/shops/new.html.erb
<h1>New shop</h1>

<%= render "form", form: @form %>

<br>

<div>
  <%= link_to "Back to shops", shops_path %>
</div>

app/views/shops/show.html.erb
<p style="color: green"><%= notice %></p>

<h1>Shop</h1>

<%= render @shop %>

<h2>Books</h2>
<%= render @shop.books %>

<div>
  <%= link_to "Edit this shop", edit_shop_path(@shop) %> |
  <%= link_to "Back to shops", shops_path %>

  <%= button_to "Destroy this shop", @shop, method: :delete %>
</div>